const prodects = [
  {
    name: "Technical club Flux",
    title: "A technical club website for demo",
    url: "https://fluxsati.netlify.app/",
    github: ["https://github.com/Anekantjainsagar/flux.git"],
    desc: "",
    skills: ["React.js"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096508/zfjiuffnahzl9gl8votx.png",
  },
  {
    name: "Textutils",
    title: "Text analyser and converter",
    url: "https://textutils-test.netlify.app/",
    github: ["https://github.com/Anekantjainsagar/TxtUtil.git"],
    desc: "",
    skills: ["React.js"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096310/b16slxdbttrdcelr1aql.png",
  },
  {
    name: "Niyamax",
    title: "Amazing lights at low prices",
    url: "https://anekantjainsagar.github.io/foodiesFront/",
    github: ["https://github.com/Anekantjainsagar/Niyamax.git"],
    desc: "",
    skills: ["HTML", "CSS", "JavaScript"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096040/cszpj0jqiucxsdu7mucz.png",
  },
  {
    name: "FarmRent",
    title: "Farming Tools for Rent",
    url: "https://farmrent.netlify.app/",
    github: ["https://github.com/Pushpendra766/farmtool-rent.git"],
    desc: "",
    skills: ["React.js", "Tailwind", "FireBase"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692095380/gveohepgiz7udhssvxzk.png",
  },
  {
    name: "Hirexa",
    title: "Soft skills test Automation",
    url: "",
    github: ["https://github.com/WittyhacksCR003/WH013_Unstoppable.gits"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692094965/fqjdy4ckspovyvkrnseh.png",
    desc: "",
    skills: [
      "Python",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "Machine Learning",
    ],
  },
  {
    name: "Sociopath",
    title: "Social Media App for Coders",
    url: "http://52.66.254.254/",
    github: ["https://github.com/Anekantjainsagar/Sociopath.git"],
    desc: "",
    skills: ["React.js", "Node.js", "Express.js", "MongoDb", "Tailwind"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1691423849/u1iqb5fdskgnsagdwptm.png",
  },
  {
    name: "Portfolio",
    title: "Personal Portfolio Website",
    url: "https://anekantjainsagar.netlify.app",
    github: ["https://github.com/Anekantjainsagar/personalportfolio.git"],
    desc: "",
    skills: ["React.js", "Node.js", "Express.js", "MongoDb", "Tailwind"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1691423806/dnnea6cz6toxuk8cfbi3.png",
  },
];

export default prodects;
