const prodects = [
  {
    name: "Technical club Flux",
    title: "A technical club website for demo",
    url: "https://fluxsati.netlify.app/",
    github: ["https://github.com/Anekantjainsagar/flux.git"],
    desc: "",
    skills: ["React.js"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096508/zfjiuffnahzl9gl8votx.png",
    tag: "Personal Project",
    linkedin: "",
  },
  {
    name: "Textutils",
    title: "Text analyser and converter",
    url: "https://textutils-test.netlify.app/",
    github: ["https://github.com/Anekantjainsagar/TxtUtil.git"],
    desc: "",
    skills: ["React.js"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096310/b16slxdbttrdcelr1aql.png",
    tag: "Personal Project",
    linkedin: "",
  },
  {
    name: "Niyamax",
    title: "Amazing lights at low prices",
    url: "https://anekantjainsagar.github.io/foodiesFront/",
    github: ["https://github.com/Anekantjainsagar/Niyamax.git"],
    desc: "",
    skills: ["HTML", "CSS", "JavaScript"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692096040/cszpj0jqiucxsdu7mucz.png",
    tag: "Personal Project",
    linkedin: "",
  },
  {
    name: "FarmRent",
    title: "Farming Tools for Rent",
    url: "https://farmrent.netlify.app/",
    github: ["https://github.com/Pushpendra766/farmtool-rent.git"],
    desc: "",
    skills: ["React.js", "Tailwind", "FireBase"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692095380/gveohepgiz7udhssvxzk.png",
    tag: "Hackathon",
    linkedin: "",
  },
  {
    name: "Hirexa",
    title: "Soft skills test Automation",
    url: "",
    github: ["https://github.com/WittyhacksCR003/WH013_Unstoppable.git"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1692094965/fqjdy4ckspovyvkrnseh.png",
    desc: "",
    skills: [
      "Python",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "Machine Learning",
    ],
    tag: "Hackathon",
    linkedin: "",
  },
  {
    name: "Sociopath",
    title: "Social Media App for Coders",
    url: "",
    github: ["https://github.com/Anekantjainsagar/Sociopath.git"],
    desc: "",
    skills: ["React.js", "Node.js", "Express.js", "MongoDb", "Tailwind"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1691423849/u1iqb5fdskgnsagdwptm.png",
    tag: "Hackathon",
    linkedin: "",
  },
  {
    name: "TapKaro",
    title: "NFC Cards Website",
    url: "https://tapkaro.com/",
    github: [],
    desc: "",
    skills: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "GSAP",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1700045605/sqnqnra0l1ga88brtctj.png",
    tag: "Freelance",
    linkedin: "",
  },
  {
    name: "Raj Sarees Enterprises",
    title: "E-Commerce platform for Sarees.",
    url: "https://raj-sarees.vercel.app/",
    github: [],
    desc: "",
    skills: [
      "React.js",
      "Next.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1711662133/cfdzque6g0wlyyvlm0ej.png",
    tag: "Freelance",
    linkedin: "",
  },
  {
    name: "Whatsapp Chat Analyzer",
    title: "Analyze WhatsApp group and individual chats for insights.",
    url: "https://whatsapp-chat-analysis-tawny.vercel.app/",
    github: [
      "https://github.com/Anekantjainsagar1/ML-Learning/tree/master/Whatsapp%20Analysis",
    ],
    desc: "",
    skills: ["Next.js", "Flask", "Tailiwnd", "Data Science"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1719053029/msgw2isknnhkm5vrfubv.png",
    tag: "Personal Project",
    linkedin:
      "https://www.linkedin.com/posts/anekantjainsagar_dataanalysis-datacleaning-datascience-activity-7171156758684426240-lxlr?utm_source=share&utm_medium=member_desktop",
  },
  {
    name: "Movie Recommendation",
    title: "Bollywood Movies Recommendation Tool",
    url: "https://movie-recommendation-delta.vercel.app/",
    github: [
      "https://github.com/Anekantjainsagar1/ML-Learning/tree/master/Movie%20Recommander%20System",
    ],
    desc: "",
    skills: ["Next.js", "Flask", "Tailiwnd", "Data Science"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1719052813/eudnfpcnptdytdlkzr3g.png",
    tag: "Personal Project",
    linkedin:
      "https://www.linkedin.com/posts/anekantjainsagar_machinelearning-bollywood-recommendationsystem-activity-7175117559128621056-f9hb?utm_source=share&utm_medium=member_desktop",
  },
  {
    name: "MindBridge",
    title: "AI Featured Mental Health Website",
    url: "https://mastermindsecurities.com/",
    github: [],
    desc: "",
    skills: [
      "Next.js",
      "Tailwind",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Socket.io",
      "ML",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1719055577/ino0yj50ujuf3akaywuf.png",
    tag: "Freelance",
    linkedin: "",
  },
  {
    name: "Master Mind Securities",
    title: "For promoting the security service",
    url: "https://mastermindsecurities.com/",
    github: [],
    desc: "",
    skills: ["Next.js", "Tailwind"],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1719051878/cdy5jqjyyo6elbvibyln.png",
    tag: "Freelance",
    linkedin: "",
  },
  {
    name: "Trubuddies",
    title: "Real time chatting app with Trubuddies",
    url: "https://trubuddies.com/",
    github: [],
    desc: "",
    skills: [
      "React.js",
      "Next.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "GSAP",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1700046033/bchwyru37qx6rv9mwvr0.png",
    tag: "Freelance",
    linkedin: "",
  },
  {
    name: "Consciousleap",
    tag: "Job",
    title: "Meeting Scheduler with Therapists",
    url: "https://consciousleap.co/",
    github: [],
    desc: "",
    skills: [
      "React.js",
      "Next.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "GSAP",
      "Zoho",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1700045716/sejwkg5wmdsfroliq6ez.png",
    linkedin: "",
  },
  {
    name: "Portfolio",
    tag: "Personal",
    title: "Personal Portfolio Website",
    url: "https://anekantjainsagar.netlify.app",
    github: ["https://github.com/Anekantjainsagar/PortfolioWebsite.git"],
    desc: "",
    skills: [
      "React.js",
      "Next.js",
      "Node.js",
      "Express.js",
      "MongoDb",
      "Tailwind",
      "GSAP",
    ],
    img: "https://res.cloudinary.com/dpbsogbtr/image/upload/v1691423806/dnnea6cz6toxuk8cfbi3.png",
    linkedin: "",
  },
];

export default prodects;
